todo_app/core/views.py
from flask import render_template,request,Blueprint


core = Blueprint('core',__name__,template_folder='templates/core')

@core.route('/')
def index():
    return render_template('main.html')

todo_app/todo/views.py
import datetime
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import current_user,login_required
from todo_app import db
from todo_app.models import User, Todo
from todo_app.todo.forms import TodoForm

todos = Blueprint('todos',__name__,template_folder='templates/todo')


@todos.route('/create', methods=['GET','POST'])
@login_required
def create_todo():

    form = TodoForm()

    if form.validate_on_submit():

        todo = Todo(text=form.text.data,date=form.date.data,user_id=current_user.username)
        db.session.add(todo)
        db.session.commit()
        flash('Task Created!', 'info')
        return redirect(url_for('users.all_user_todos', username=current_user.username))

    return render_template('create_todo.html',form=form)

@todos.route('/todo/<int:todo_id>')
@login_required
def todo(todo_id):
    todos = Todo.query.get_or_404(todo_id)
    return render_template('todo.html',todos=todos)

@todos.route("/<int:todo_iid>/update_todo", methods=['GET', 'POST'])
@login_required
def update_todo(todo_iid):
    todo = Todo.query.get_or_404(todo_iid)
    if todo.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = TodoForm()
    if form.validate_on_submit():
        todo.text = form.text.data
        todo.date = form.date.data
        db.session.commit()
        flash('Task Updated', 'info')
        return redirect(url_for('users.all_user_todos', username=current_user.username))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.text.data = todo.text
        form.date.data = todo.date

    return render_template('create_todo.html',form=form,todo=todo)

@todos.route("/<int:todo_id>/delete", methods=['POST'])
@login_required
def delete_todo(todo_id):
    todo = Todo.query.get_or_404(todo_id)
    if todo.author != current_user:
        abort(403)
    db.session.delete(todo)
    db.session.commit()
    flash('Task has been deleted', 'danger')
    return redirect(url_for('users.all_user_todos',username=current_user.username))

todo_app/users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint,session
from flask_login import login_user, current_user, logout_user, login_required
from todo_app import db, app, bcrypt
from todo_app.models import User, Todo
from todo_app.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm, Change_DpForm, UpdateUserForm
from todo_app.users.token import get_token, verify_token
from todo_app.users.email import send_reset_email
from todo_app.users.picture import save_picture


users = Blueprint('users',__name__,template_folder='templates/users')


@users.route('/register', methods=['GET','POST'])
def register():

    form = RegistrationForm()

    if form.validate_on_submit():

        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(email=form.email.data,username=form.username.data,first_name=form.first_name.data,last_name=form.last_name.data,gender=form.gender.data,password=hashed_password)

        db.session.add(user)
        db.session.commit()

        flash('Registration Completed', 'info')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)


@users.route('/login', methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user is None:
            flash('This is no user with this email. Please check the email or Register!', 'danger')

        elif bcrypt.check_password_hash(user.password, form.password.data) and user is not None:
            login_user(user, remember=form.remember.data)
            # session['username'] = user.username

            flash('Welcome On-board', 'info')
            # return redirect(url_for('users.all_user_todos', username=current_user.username))

            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('core.index')
            return redirect(next)

        elif bcrypt.check_password_hash(user.password, form.password.data) is None or user is not None:
            flash('Incorrect password', 'danger')

        else:
            flash('Login Unsuccessful. Please check email or password', 'danger')

    return render_template('login.html', form=form)


@users.route("/logout")
def logout():
    logout_user()
    flash('Logout successful', 'info')
    return redirect(url_for("core.index"))



#send_reset_email
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):

    user = verify_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password Updated! log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password',form=form)


@users.route("/<username>", methods=['GET','POST'])
def user_todos(username):

    user = User.query.filter_by(username=username).first_or_404()

    form = Change_DpForm()
    if form.validate_on_submit():

        if form.picture.data:
            pic = save_picture(form.picture.data)
            current_user.profile_image = pic
        db.session.commit()
        flash('Profile Image Updated!', 'info')
        return redirect(url_for('users.user_todos', username=current_user.username))

    ROWS_PER_PAGE = 4
    page = request.args.get('page',1,type=int)
    todos = Todo.query.filter_by(author=user).order_by(Todo.date.desc()).paginate(page=page,per_page=ROWS_PER_PAGE)
    return render_template('user_todos.html',todos=todos,user=user,page=page,form=form)


@users.route("/todo/<username>", methods=['GET','POST'])
def all_user_todos(username):

    user = User.query.filter_by(username=username).first_or_404()
    ROWS_PER_PAGE = 5
    page = request.args.get('page',1,type=int)
    todos = Todo.query.filter_by(author=user).order_by(Todo.date.asc()).paginate(page=page,per_page=ROWS_PER_PAGE)
    return render_template('all_user_todo.html',todos=todos,user=user,page=page)

@users.route('/account', methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():

        current_user.username = form.username.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        db.session.commit()
        flash('User Account Updated!', 'info')
        return redirect(url_for('users.user_todos', username=current_user.username))

    elif request.method == 'GET':
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.username.data = current_user.username

    return render_template('account.html',form=form)

todo_app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style media="screen">
    @media only screen and (max-width:600px){.sec{margin-bottom:15px}}.navigation{background-color:#000}body{min-height:100vh;display:flex;flex-direction:column}footer{margin-top:auto;padding:25px 0;background:#111;border-top:2px solid #28ABE3}.copyright{text-transform:uppercase;text-transform:none;color:#999}.footer-social li{display:inline;padding:0 10px}.footer-social li a{padding:8px;color:#fff;background:#28ABE3}.footer-social li i{font-size:15px;width:20px;height:20px}.footer-social li:hover a{background:#fff;color:#666}.footer-link li{display:inline;padding-left:10px;font-size:13px}.btn:focus,.btn:active,.btn.active,.btn:active:focus{outline:0}.footer-social li{display:inline;padding:0 10px}.footer-social li a{padding:8px;color:#fff;-webkit-border-radius:2px;-moz-border-radius:2px;-o-border-radius:2px;border-radius:2px}.footer-social li i{font-size:15px;width:20px;height:20px}.footer-social li:hover a{background:#fff;color:#666}.footer-link li{display:inline;padding-left:10px;font-size:13px}.mid{margin: auto;}
    </style>
    <link rel="shortcut icon" href="{{url_for('static',filename='images/logo.png.png')}}">
    <title>{% block title %}{% endblock %} - Fenom</title>
    {% endblock %}
  </head>
  <body>

    <section class="navigation">
      <div class="container-fluid navBackground">
        <nav class="navbar navbar-expand-lg navbar-dark scrolling-navbar sticky-top">
          <a class="navbar-brand mr-4" href="{{ url_for('core.index') }}">Fenom</a>
          <!-- <a class="navbar-brand" href="index.html"><img src="{{url_for('static',filename='images/logo.png.png')}}" alt="logo" style="width: 50px; height: auto;"></a> -->

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('core.index') }}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">

              {% if current_user.is_authenticated %}

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Todo
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{{ url_for('todos.create_todo') }}">Add Task</a>
                  <a class="dropdown-item" href="{{ url_for('users.all_user_todos', username=current_user.username) }}">Tasks</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{{ url_for('users.user_todos', username=current_user.username) }}">Profile</a>
                  <a class="dropdown-item" href="{{ url_for('users.account') }}">Edit Profile</a>
                </div>
              </li>

              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>

              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}

            </div>

          </div>
        </nav>
      </div>
    </section>

    <div class="mid">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div>

    {% block content %}

    {% endblock %}




    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-xs-12 sec">
            <span class="copyright"> &copy; Fenom 2022. Designed by Shabzynana</span>
          </div>
          <div class="col-md-4 col-xs-12">
            <div class="footer-social text-center">
              <ul>
                <li class="waves-effect"><a href="https://twitter.com/Shabzynana"><i class="fa fa-twitter"></i></a></li>
                <li class="waves-effect"><a href="https://github.com/Shabzynana"><i class="fa fa-github"></i></a></li>
                <li class="waves-effect"><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li class="waves-effect"><a href="https://www.instagram.com/shabzynana/"><i class="fa fa-instagram"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>


    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% endblock %}
  </body>
</html>